### ISSUE TITLE
Échanger deux salles

### ISSUE THREAD

**Issue by ysalmon** [ynaessens/GRR#1]
Bonjour Yan,

je vois que tu as fait plein de contributions à GRR dans une pull request.

Est-ce que tu t'es penché sur la possibilité d'échanger les salles de deux réservations ?
J'ai ouvert une issue sur upstream à ce sujet https://github.com/JeromeDevome/GRR/issues/42

**Comment by ynaessens** [comment]
Bonjour Yann,
j'ai lu ta demande https://github.com/JeromeDevome/GRR/issues/42
évidemment intéressante, tu verrais cela sous quelle forme ?

**Comment by ysalmon** [comment]
Je ne sais pas trop.

Je me disais quand sur l'écran qui signale les conflits et propose de supprimer les réservations qui entrent en conflit avec celle qu'on veut faire, on pourrait avoir une option pour échanger les salles au lieu de supprimer, lorsque cet écran survient alors qu'on est en train de modifier la salle d'une réservation existante plutôt que d'en créer une nouvelle.

Mais c'est peut-être un peu compliqué, voire pas ergonomique. On pourrait aussi envisager que dans l'écran de détail de réservation, il y ait un bouton spécifique pour échanger la salle. Ça amènerait à un écran qui présenterait seulement les réservations qui ont lieu en même temps ; ça serait plus simple, quelque part. La difficulté étant que pour les réservations récurrentes, la liste des réservations qui ont lieu en même temps peut varier d'une occurrence à l'autre ; il faudrait ne considérer que les réservations qui sont également récurrentes, probablement.

J'ai regardé un peu le code mais procéder à l'échange proprement et sans risque nécessite une compréhension assez fine de comment sont enregistrées et gérées les choses ; ça me dépasse.

Le code sur lequel je me base est celui de la version de GRR du GIP Récia (le GIP de la Région Centre qui gère les infrastructures informatiques et l'ENT) https://github.com/GIP-RECIA/GRR-MuE

**Comment by ynaessens** [comment]
Bonjour Yann,
Je vois mieux à quoi tu penses.
Je ne te cacherai pas que c'est intéressant et que j'ai encore des
corrections à faire sur la version "Devome".
Je garde l'idée et te ferai signe lorsque j'ouvrirai ce chantier.

**Comment by ynaessens** [comment]
Bonjour Yann,
j'ai fait une première proposition de scripts répondant à ta question.
Dis-moi si cela répond à ton attente, et si cela peut être proposé à la communauté.
Il sera peut-être nécessaire d'adapter le code à GRR-MuE du GIP Récia.

**Comment by ysalmon** [comment]
Bonjour,
j'ai enfin le temps de jeter un œil à tout ça !
Merci pour le commit ; je l'ai signalé aux collègues du Recia https://github.com/GIP-RECIA/GRR-MuE/issues/15

De notre côté, l'administration est en train d'abandonner GRR pour réintégrer la gestion de ces salles dans Pronote (utilisé pour toutes les autres salles)…
